export interface CharacterSkills {
    Ref : number,
    CharacterRef : number,
    Acrobatics : number,
    AnimalHandling : number,
    Arcana : number,
    Athletics : number,
    Deception : number,
    History : number,
    Insight : number,
    Intimidation : number,
    Investigation : number,
    Medicine : number,
    Nature : number,
    Perception : number,
    Performance : number,
    Persuasion : number,
    Religion : number,
    SleightOfHand : number,
    Stealth : number,
    Survival : number
};
