export interface CharacterSkills {
    ref? : number,
    characterRef? : number,
    acrobatics? : number,
    animalHandling? : number,
    arcana? : number,
    athletics? : number,
    deception? : number,
    history? : number,
    insight? : number,
    intimidation? : number,
    investigation? : number,
    medicine? : number,
    nature? : number,
    perception? : number,
    performance? : number,
    persuasion? : number,
    religion? : number,
    sleightOfHand? : number,
    stealth? : number,
    survival? : number
};

export interface CharacterSkillsProfiency {
    acrobatics? : boolean,
    animalHandling? : boolean,
    arcana? : boolean,
    athletics? : boolean,
    deception? : boolean,
    history? : boolean,
    insight? : boolean,
    intimidation? : boolean,
    investigation? : boolean,
    medicine? : boolean,
    nature? : boolean,
    perception? : boolean,
    performance? : boolean,
    persuasion? : boolean,
    religion? : boolean,
    sleightOfHand? : boolean,
    stealth? : boolean,
    survival? : boolean
};